[commit]
conventional_commits = true
filter_unconventional = true
tag_prefix = "v"
tag_name = "v{{version}}"
pre_bump_hooks = []
post_bump_hooks = []

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "legra-ai"
repository = "tokio-token-bucket"
